import { useCallback, useState } from "react";
import { AlertTriangle, ExternalLink, Gift, Radio, Smartphone, WifiOff, X } from "lucide-react";
import { ConfirmDialog } from "./ConfirmDialog";
import type { AgentSession, AgentState, StatusIcon } from "../hooks/useAgent";

interface AgentPanelProps { onClose: () => void; onBind: () => void; onRedeem: () => void; onUnbind: () => Promise<{ ok: boolean; error?: string }>; onCheckUpdate?: () => void; agent: AgentState; }
export function buildKillSessionIpcArgs(session: AgentSession) { return { method: "kill_session", params: { nid: session.nid, reason: "process_killed" } }; }
const labels: Record<StatusIcon, string> = { offline: "电脑端未运行", unbound: "设备未绑定", binding: "绑定中…", connected: "已连接", reconnecting: "重新连接中…", upgrade_required: "需要升级桌面端", starting: "启动中…" };
const dots: Record<StatusIcon, string> = { offline: "bg-gray-400", unbound: "bg-app-amber", binding: "bg-app-accent animate-pulse", connected: "bg-app-green", reconnecting: "bg-app-amber animate-pulse", upgrade_required: "bg-app-red animate-pulse", starting: "bg-app-accent animate-pulse" };

export function AgentPanel({ onClose, onBind, onRedeem, onUnbind, onCheckUpdate, agent }: AgentPanelProps) {
  const [confirmUnbind, setConfirmUnbind] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  const unbind = useCallback(async () => { setBusy(true); const result = await onUnbind(); setBusy(false); setConfirmUnbind(false); if (!result.ok) setError(`解除绑定失败：${result.error ?? "未知错误"}`); }, [onUnbind]);
  const recover = useCallback(async (repair: boolean) => { setBusy(true); const result = await (repair ? agent.repairAgent() : agent.restartAgent()); setBusy(false); if (!result.ok) setError(`${repair ? "修复安装" : "重启"}失败：${result.error ?? "未知错误"}`); }, [agent]);
  const status = agent.agentStatus; const access = status?.remote_access;
  return <><div className="fixed inset-0 z-[120] flex items-start justify-end p-4 pt-12" onClick={onClose}><section className="app-dialog-panel bg-app-panel border border-app-border w-[360px] max-h-[calc(100vh-4rem)] flex flex-col" onClick={(event) => event.stopPropagation()} aria-label="手机远程控制">
    <header className="flex shrink-0 items-center justify-between px-4 py-3 border-b border-app-border"><div className="flex items-center gap-2"><Smartphone size={16} className="text-app-accent" /><div><h2 className="text-sm font-semibold text-app-text">手机远程控制</h2><p className="text-[10px] text-app-text-muted">管理手机对这台 Mac 的访问权限</p></div></div><button type="button" onClick={onClose} aria-label="关闭手机远程控制" className="p-1 text-app-text-dim hover:text-app-text"><X size={15} /></button></header>
    <div className="min-h-0 overflow-y-auto p-4 space-y-4"><section className="flex flex-col items-center gap-2 py-3 text-center"><span className={`w-3 h-3 rounded-full ${dots[agent.statusIcon]}`} /><p className="text-base font-semibold text-app-text">{labels[agent.statusIcon]}</p>{status?.hostname && <p className="text-xs font-mono text-app-text-muted">{status.hostname}</p>}{agent.isConnected && access && <p className={access.allowed ? "text-[11px] text-app-green" : "text-[11px] text-app-amber"}>{access.allowed ? (access.expiresAt ? `会员有效期至 ${access.expiresAt.slice(0, 10)}` : "远程权限正常") : (access.message || "远程会话暂不可用")}</p>}</section>
      {error && <div role="alert" className="px-3 py-2 text-xs text-app-red bg-app-red/10 border border-app-red/30">{error}</div>}<div className="space-y-2">{agent.isRunning && !agent.isBound && !agent.isBinding && <><button type="button" onClick={onBind} className="app-primary-action w-full px-3 py-2 text-sm font-medium flex justify-center items-center gap-2"><Radio size={14} />绑定设备</button><p className="text-center text-xs text-app-text-muted">绑定后即可用手机远程控制 Mac</p></>}{agent.isBinding && <div className="px-3 py-2 text-sm text-center text-app-text-dim bg-[var(--app-cmd-bg)] border border-app-border">正在绑定中…</div>}{status?.state === "upgrade_required" && <><div className="text-xs text-app-red text-center"><AlertTriangle size={13} className="inline mr-1" />服务器要求升级后才能恢复远程控制</div><button type="button" onClick={onCheckUpdate} className="w-full px-3 py-2 text-xs border border-app-red text-app-red hover:bg-app-red/10">检查并升级</button></>}{agent.isConnected && <><button type="button" onClick={onRedeem} className="w-full px-3 py-2 text-sm border border-app-accent text-app-accent hover:bg-app-accent hover:text-app-bg flex justify-center items-center gap-2"><Gift size={14} />兑换码</button><button type="button" onClick={() => setConfirmUnbind(true)} className="w-full px-3 py-2 text-sm border border-app-red/50 text-app-red hover:bg-app-red/10 flex justify-center items-center gap-2"><WifiOff size={14} />解除本机绑定</button></>}{status?.purchase_url && <a href={status.purchase_url} target="_blank" rel="noopener noreferrer" className="w-full px-3 py-2 text-sm border border-app-border text-app-text-dim hover:text-app-text flex justify-center items-center gap-2 no-underline"><Gift size={14} />购买兑换码<ExternalLink size={11} /></a>}</div>{!agent.isRunning && <section className="border-t border-app-border pt-4 space-y-2"><p className="text-center text-xs text-app-text-muted">kn-agent 未运行，远程控制已禁用</p><div className="grid grid-cols-2 gap-2"><button type="button" disabled={busy} onClick={() => void recover(false)} className="px-2 py-2 text-xs border border-app-border text-app-text-dim disabled:opacity-40">重启 Agent</button><button type="button" disabled={busy} onClick={() => void recover(true)} className="px-2 py-2 text-xs border border-app-accent text-app-accent disabled:opacity-40">修复安装</button></div></section>}</div>
  </section></div><ConfirmDialog open={confirmUnbind} title="解除本机绑定" message="这会立即关闭全部远程会话、撤销本机设备凭证，并使手机无法继续控制这台 Mac。本地配置和 CLI 不受影响。" confirmLabel="解除绑定" variant="danger" loading={busy} onConfirm={() => void unbind()} onCancel={() => setConfirmUnbind(false)} /></>;
}
